### ISSUE TITLE
Fix iscompatible function to not fail if exception

### ISSUE THREAD

**Issue by brauth** [kirk-quinbar/HeartRateLE#4]
private async Task<bool> IsDeviceCompatible(string deviceId)
        {
            var compatibleDevice = true;
            try
            {
                var device = await BluetoothLEDevice.FromIdAsync(deviceId);

                //if filters were passed, check if the device name contains one of the names in the list
                if (_filters != null)
                {
                    compatibleDevice = _filters.Any(a => device.Name.CaseInsensitiveContains(a));
                }

                //filter out any devices that are not heart rate devices. with the current bluetooth apis, this will
                //only occur if the device is paired. the windows creator update is supposed to allow for checking for this
                //on unpaired devices, but a recent build completely broke bluetooth le support, so this is the best
                //that can be done for now.
                if (device.GattServices.Any() && compatibleDevice)
                {
                    bool matches = true;
                    foreach (var requiredService in RequiredServices)
                    {
                        matches = CheckForCompatibility(device, requiredService.ToGuid());
                        if (!matches)
                            break;
                    }
                    compatibleDevice = matches;
                }
            }
            catch
            {

                compatibleDevice = false;
            }

            return compatibleDevice;
        }

**Comment by kirk-quinbar** [comment]
added try/catch to this method. not sure why the signature copied the way it did. it should be as below and return a bool.

private async Task<bool> IsDeviceCompatible(string deviceId)
