### ISSUE TITLE
Check if bluetooth support available

### ISSUE THREAD

**Issue by marcellangmaier** [kirk-quinbar/HeartRateLE#6]
Your code works perfect in windows update 1709. I was able to create a WinForms application receiving measurements from a Polar H7.
I was looking for a method to check weather bluetooth support is available on the machine, but did not find any. Somewhere in the internet I found a code snippet like this:

        public static async Task<bool> BluetoothIsSupportedAsync()
        {
            var radios = await Radio.GetRadiosAsync();
            var bluetoothRadio = radios.FirstOrDefault(radio => radio.Kind == RadioKind.Bluetooth);
            return bluetoothRadio != null;
        }

But this isn't working. The GetRadiosAsync function is returning a __ComObject which cannot be evaluated.
Do you have any idea how to check if bluetooth is supported, bluetooth is enabled, bluetooth le is available.... ?
Brgds
Marcel

**Comment by nikname** [comment]
You can use BluetoothLEAdvertisementWatcher class.

```
var _advWatcher = new BluetoothLEAdvertisementWatcher();

_advWatcher.Start();
Thread.Sleep(100);
_advWatcher.Stop();

if (_advWatcher.Status == BluetoothLEAdvertisementWatcherStatus.Aborted)
{
    Debug.WriteLine("Bluetooth is disabled or not available");
}
```

You can even register for advertisements. If Bluetooth is disabiled or not available you will receive no advertisement.

```
// before _advWatcher.Start()
_advWatcher.Received += AdvWatcher_Received;
```
```
private void AdvWatcher_Received(BluetoothLEAdvertisementWatcher sender,
    BluetoothLEAdvertisementReceivedEventArgs e)
{
    Debug.WriteLine("Advertisement received. Bluetooth is available!");
}
```

Hope this help!
